- inference_steps: 25
  guidance_scale: 8
  lr: 0.01
  opt_iters: 5
  PCA_dim: 64
  opt_step: 5
  compress_factor: 4
  load_feature_step: 3
  inversion_timestep: 201
  debias_patch_size: 4
  opt_attn_list: [1, 3]
  load_attn_list: [0, 1, 3, 4]
  load_res_list: [3, 4, 6, 7]